name: Create Secret With Akeyless

on:
  workflow_dispatch:

jobs:
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new secret in Akeyless
        uses: your-fork/akeyless-github-action@your-branch
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          create-secret-name: "/my/new/secret"
          create-secret-value: "SuperSecretValue123"
