name: Akeyless Fetch Secrets - Manual

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Akeyless and fetch secret manually
        env:
          AKEYLESS_API: https://api.akeyless.io
          AKEYLESS_ACCESS_ID: ${{ secrets.AKEYLESS_ACCESS_ID }}
          AKEYLESS_ACCESS_KEY: ${{ secrets.AKEYLESS_ACCESS_KEY }}
        run: |
          echo "Authenticating to Akeyless..."
          TOKEN=$(curl -s --request POST "$AKEYLESS_API/auth" \
            --header "Content-Type: application/json" \
            --data '{
              "access-id": "'"$AKEYLESS_ACCESS_ID"'",
              "access-key": "'"$AKEYLESS_ACCESS_KEY"'"
            }' | jq -r '.token')

          echo "Fetching secret..."
          DB_PASSWORD=$(curl -s --request POST "$AKEYLESS_API/get-secret-value" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer $TOKEN" \
            --data '{
              "name": "/secret_for_guthub_actions_test"
            }' | jq -r '.value')

          echo "Fetched DB Password: $DB_PASSWORD"
