name: TEST Akeyless Forked Action

on:
  workflow_dispatch:

jobs:
  test-akeyless-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my Forked Akeyless Action
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          static-secrets: |
            - name: "/MCP/GEMINI_API_KEY"
              output-name: "SECRET_VALUE"

      - name: Print fetched secret
        run: echo "Fetched Secret: ${{ steps.fetch-secrets.outputs.SECRET_VALUE }}"
