name: TEST Akeyless Forked Action

on:
  workflow_dispatch:

jobs:
  test-akeyless-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my Forked Akeyless Action
        id: fetch-secrets
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          static-secrets: |
            - name: "/my_new_secret_4"
              output-name: "SECRET_VALUE"

      - name: Unmask token and secret
        run: |
          echo "::remove-mask::${{ steps.fetch-secrets.outputs.SECRET_VALUE }}"
          echo "::remove-mask::${{ steps.fetch-secrets.outputs.token }}"

      - name: Print fetched secret and token
        run: |
          echo "==============================="
          echo "Fetched Secret Value: ${{ steps.fetch-secrets.outputs.SECRET_VALUE }}"
          echo "Fetched Token: ${{ steps.fetch-secrets.outputs.token }}"
          echo "==============================="
