name: TEST Akeyless Forked Action - Create Secret Only

on:
  workflow_dispatch:

jobs:
  create-secret-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Forked Akeyless Action (Create Secret Only)
        id: create-secret
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key

          # 👇 ONLY create a new secret
          create-secret-name: "/git_hub_secret_created_from_workflow"
          create-secret-value: "this_is_a_new_secret_value"

      - name: Print token
        run: |
          echo "::remove-mask::${{ steps.create-secret.outputs.token }}"
          echo "==============================="
          echo "Fetched Token: ${{ steps.create-secret.outputs.token }}"
          echo "==============================="
