name: Update Secret With Akeyless 3

on:
  workflow_dispatch:

jobs:
  update_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Update an existing secret in Akeyless
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          update-secret-name: "/my_new_secret_5"
          update-secret-value: "UpdatedSuperSecretValue456"
