name: Akeyless Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # If using GitHub OIDC login

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate and Fetch Secrets
        uses: akeyless-community/github-action@main   # <-- HERE!!
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          secrets: |
            DB_PASSWORD=/path/to/db-password
            API_KEY=/path/to/api-key
