name: Create Secret With Akeyless 3

on:
  workflow_dispatch:

jobs:
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Create a new secret in Akeyless
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          create-secret-name: "/my_new_secret_3"
          create-secret-value: "SuperSecretValue123"
