name: Create Secret With Akeyless

on:
  workflow_dispatch:

jobs:
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new secret in Akeyless
        uses: Akeyless-Product-Team/akeyless-github-action@main
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          create-secret-name: "my_new_secret"
          create-secret-value: "SuperSecretValue123"
